apiVersion: v1
kind: ConfigMap
metadata:
  name: "nginx-configmap"
data:
  nginx.conf: |
        server {
                listen 80;
                server_name _;
                root /var/www/data;
        
                index index.html;
        
                location / {
                }
        }
